### ISSUE TITLE
Is this tool possibly usable with linux-surface kernel?

### ISSUE THREAD

**Issue by kuanyui** [ANDRoid7890/bootsplash-manager#4]
Sorry, I have no knowledge about kernel, so my question may be very dumb... I want to know is this tool possibly usable with linux-surface kernel?

I installed & using [kernel provided by linux-surface](https://github.com/linux-surface/linux-surface) on my Manjaro, and it shows:

![Screenshot_20211215_120019](https://user-images.githubusercontent.com/1370070/146120802-1c6e5c6c-8b88-4014-a4f3-21080bc280d6.png)

I've tried, it indeed... unworkable currently.

Thanks.

**Comment by ANDRoid7890** [comment]
the question is not about supporting some kernels by this tool
bootsplash is a part of kernel that should be provided by a patch
As I can see, your kernel doesn't contain these patches

**Comment by ANDRoid7890** [comment]
You can find bootsplash patches here https://gitlab.manjaro.org/packages/core/linux513
