### ISSUE TITLE
Is it possible to customize your own logo or load original firmware logo from BIOS

### ISSUE THREAD

**Issue by Zesko** [ANDRoid7890/bootsplash-manager#7]
Out of my curiosity, is it possible to implement that Bootsplash-Manager loads any chosen picture (.png .jpg .gif) and compiles it in binary for Bootsplash?

**Comment by ANDRoid7890** [comment]
Maybe i'll make an editor in future
You can replace source files from [another theme](https://github.com/openmindead/bootsplash-theme-manjaro-muser) to make your own one
